# Generated by Django 4.1.3 on 2022-11-09 15:27

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.auth.models import Group, User


def add_default_groups(apps, schema_editor):
    attendee_group, created = Group.objects.get_or_create(name="Attendees")

    attendee_group.permissions.add(
        Permission.objects.get(name="Can view sent invitations"))
    attendee_group.permissions.add(
        Permission.objects.get(name="Can view received invitations"))
    attendee_group.permissions.add(
        Permission.objects.get(name="Can send invitation"))
    attendee_group.permissions.add(
        Permission.objects.get(name="Can accept invitation"))

    attendee_group.permissions.add(
        Permission.objects.get(name="Can view event"))
    attendee_group.permissions.add(
        Permission.objects.get(name="Can view user profile"))


def remove_default_groups(apps, schema_editor):
    attendee_group = Group.objects.get("Attendees")

    attendee_group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('meetme_app', '0002_save_permissions'),
    ]

    operations = [
        migrations.RunPython(add_default_groups, remove_default_groups)
    ]
