# Generated by Django 4.1.3 on 2022-11-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme_app', '0004_alter_event_registered_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.TextField(default='Bologna'),
            preserve_default=False,
        ),
    ]
