# Generated by Django 4.1.3 on 2022-11-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme_app', '0004_alter_meetingrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrequest',
            name='acknowledge_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('ACK', 'Accepted'), ('NAK', 'Rejected')], max_length=6, null=True),
        ),
    ]
